# **LSTM vs GRU Comparision for Sentiment Analysis**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dense
from sklearn.model_selection import train_test_split

In [ ]:
texts = [
"Artificial intelligence is amazing",
"I love deep learning", "This course is excellent", "I am very happy today", "The movie was fantastic",
"I hate this product",
"This is very bad",
"The service was terrible",
"I am disappointed",
"The experience was awful"
]
labels=[1,1,1,1,1,0,0,0,0,0]

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(texts)
sequences=tokenizer.texts_to_sequences(texts)
max_length=max([len(seq) for seq in sequences])
X=pad_sequences(sequences,maxlen=max_length)
y=np.array(labels)
print("X=",X)
print("y=",y)

X= [[ 0  8  9  2 10]
 [ 0  1 11 12 13]
 [ 0  3 14  2 15]
 [ 1  6  7 16 17]
 [ 0  4 18  5 19]
 [ 0  1 20  3 21]
 [ 0  3  2  7 22]
 [ 0  4 23  5 24]
 [ 0  0  1  6 25]
 [ 0  4 26  5 27]]
y= [1 1 1 1 1 0 0 0 0 0]


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# **LSTM Model**

In [ ]:
lstm_model=Sequential([
Embedding(
input_dim=len(tokenizer.word_index)+1,
output_dim=16,
input_length=max_length
),
LSTM(64),
Dense (1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
lstm_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
lstm_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history_lstm=lstm_model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,verbose=1)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.6250 - loss: 0.6926 - val_accuracy: 0.5000 - val_loss: 0.6935
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6250 - loss: 0.6920 - val_accuracy: 0.0000e+00 - val_loss: 0.6934
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6250 - loss: 0.6913 - val_accuracy: 0.0000e+00 - val_loss: 0.6933
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.8750 - loss: 0.6907 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.8750 - loss: 0.6899 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.8750 - loss: 0.6891 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8750 - loss: 0.6883 - val_accuracy: 1.0000 - val_loss: 0.6930
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.6874 - val_accuracy: 0.5000 - val_loss:

In [ ]:
lstm_loss, lstm_acc=lstm_model.evaluate(
X_test,
y_test,
verbose=0
)
print(f"LSTM Loss: {lstm_loss:.4f}")
print(f"LSTM Accuracy: {lstm_acc:.4f}")

LSTM Loss: 0.6924
LSTM Accuracy: 0.5000


# **GRU Model**

In [ ]:
gru_model=Sequential([
    Embedding(
        input_dim=len(tokenizer.word_index)+1,
        output_dim=16,
        input_length=max_length
    ),
    GRU(32),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
gru_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
gru_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_2 (GRU)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history_gru=gru_model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,verbose=1)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5000 - loss: 0.6914 - val_accuracy: 0.5000 - val_loss: 0.6929
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.8750 - loss: 0.6905 - val_accuracy: 0.5000 - val_loss: 0.6928
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8750 - loss: 0.6895 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8750 - loss: 0.6885 - val_accuracy: 0.5000 - val_loss: 0.6925
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.6874 - val_accuracy: 0.5000 - val_loss: 0.6924
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.6863 - val_accuracy: 0.5000 - val_loss: 0.6923
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8750 - loss: 0.6851 - val_accuracy: 0.5000 - val_loss: 0.6922
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 1.0000 - loss: 0.6839 - val_accuracy: 0.5000 - val_loss: 0.6922
Ep

In [ ]:
gru_loss, gru_acc=gru_model.evaluate(
X_test,
y_test,
verbose=0
)
print(f"GRU Loss: {gru_loss:.4f}")
print(f"GRU Accuracy: {gru_acc:.4f}")

GRU Loss: 0.6926
GRU Accuracy: 0.5000


In [ ]:
print('Model Comparision')
print(f'LSTM Loss: {lstm_loss:.4f}')
print(f'LSTM Accuracy: {lstm_acc:.4f}')
print(f'GRU Loss: {gru_loss:.4f}')
print(f'GRU Accuracy: {gru_acc:.4f}')

Model Comparision
LSTM Loss: 0.6924
LSTM Accuracy: 0.5000
GRU Loss: 0.6926
GRU Accuracy: 0.5000


In [ ]:
def predict_sentiment(text, model):
    sequence = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequence, maxlen=max_length)
    prediction = model.predict(padded,verbose=0)[0][0]
    if prediction > 0.5:
        return "Positive", prediction
    else:
        return "Negative", prediction

In [ ]:
text="I love artificial Intelligence"
result,score=predict_sentiment(
    text,
    lstm_model
)
print(f"LSTM Prediction:")
print(result,score)

LSTM Prediction:
Positive 0.513937


In [ ]:
text="I love artificial Intelligence"
result,score=predict_sentiment(
    text,
    gru_model
)
print(f"GRU Prediction:")
print(result,score)

GRU Prediction:
Positive 0.5096687


In [ ]:
text="I want to die "
result,score=predict_sentiment(
    text,
    lstm_model
)
print(f"LSTM Prediction:")
print(result,score)

LSTM Prediction:
Negative 0.4815971
